server:
  servlet:
    context-path: /api/v1  # Base path for all API endpoints
  port: 8088

spring:
  profiles:
    active: dev,test
  servlet:
    multipart:
      max-file-size: 50MB  # Maximum file size for file uploads (optional)

springdoc:
  default-produces-media-type: application/json  # Default media type for Swagger API responses

  security:
    user:
      name: vani  # Username for HTTP basic authentication (optional)
      password: 123  # Password for HTTP basic authentication (optional)

management:
  endpoints:
    web:
      exposure:
        include: beans,loggers,metrics,health,info,readiness  # Expose specific Spring Boot Actuator endpoints for monitoring